export { default as PageNotFound } from "./404Page";
export { default as CartPage } from "./CartPage";
export { default as CategoryPage } from "./CategoryPage";
export { default as ConfirmationPage } from "./ConfirmationPage";
export { default as HomePage } from "./HomePage";
export { default as ProductPage } from "./ProductPage";
export { default as PromotionalPage } from "./PromotionalPage";
export { default as ShopPage } from "./ShopPage";
export { default as SupportPage } from "./SupportPage";
